Add Swift example for managing NFT allowances
hashgraph/hedera-sdk-swift pull request #400
Opened 2024-10-22 07:45 UTC by b-l-u-e

**Description**:

**Testing**:

- Due to not having access to a macOS or iOS environment, I am unable to run the example locally.
- I have followed the requirements and provided the steps as per the Swift SDK documentation.
- I request assistance from the maintainers or anyone with access to a macOS environment to test this example and verify that it functions as expected.

**Related issue(s)**:

Fixes #385: Add example: Add and remove NFT allowances

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments,)
- [ ] Tested (unit, integration, etc.)

2024-10-22 07:48 UTC, b-l-u-e commented
Requesting for assistance on testing this one @hendrikebbers

2024-10-24 05:29 UTC, b-l-u-e commented
Hello need help with testing. Anyone please @kenthejr @dalvizu @mehcode

2024-10-24 18:06 UTC, RickyLB commented
Hi @b-l-u-e, I manage the Swift SDK. Do you need help running the example?

> Hello need help with testing. Anyone please @kenthejr @dalvizu @mehcode

2024-10-24 18:41 UTC, RickyLB commented
> Hello need help with testing. Anyone please @kenthejr @dalvizu @mehcode

Hi @b-l-u-e, thank you for your PR.

In `Package.swift`, add `AddNftAllowance` to the list of `exampleTargets` so the SDK detects the executable. Then run `swift run AddNftAllowanceExample`.

2024-10-24 20:10 UTC, b-l-u-e commented
@RickyLB thank you for reaching out to me.. let me add AddNftAllowance in exampleTargets

2024-10-24 20:41 UTC, b-l-u-e commented
@RickyLB just made changes

2024-10-28 10:53 UTC, b-l-u-e commented
@RickyLB  requesting for a review

2024-10-28 22:02 UTC, RickyLB requested changes

2024-10-28 22:02 UTC, RickyLB commented on Examples/AddNftAllowance/main.swift
> +        let transferReceipt = try await TransferTransaction()
`.transactionId(TransactionId.generateFrom(spenderAccountId))` should be added to this in order for the transaction to be executed on behalf of the Spender account.

2024-10-28 22:12 UTC, RickyLB commented
@b-l-u-e Apologize, I should I included this earlier. A good way to test the example would be to create a testnet account in [hedera portal](https://portal.hedera.com/register) account, and fill a new `.env` file in the SDK with the following ECDSA values from portal:

```
OPERATOR_ID=<Account Id>
# Default private key to use to sign for all transactions and queries
OPERATOR_KEY=<DER Encoded Private Key>

# Network names: `"localhost"`, `"testnet"`, `"previewnet"`, `"mainnet"`
HEDERA_NETWORK=testnet
```

2024-10-29 00:30 UTC, b-l-u-e commented
@RickyLB @mehcode @dalvizu @kenthejr requesting for a review made some changes based on your review

2024-10-29 19:17 UTC, b-l-u-e commented
@RickyLB any updates?

2024-10-30 22:27 UTC, RickyLB commented
@b-l-u-e please check the CI build errors; they will tell you why it's failing. Also, it may help to install [Swift 6.0.2](https://www.swift.org/install/windows/) on your local machine (Windows or linux) so you view these errors quicker.

2024-10-30 22:34 UTC, RickyLB requested changes

2024-10-30 22:34 UTC, RickyLB commented on Examples/AddNftAllowance/main.swift
> +            .key(receiverKey.publicKey.single())
Should be `.single(receiverKey.publicKey)`

2024-10-30 22:34 UTC, RickyLB commented on Examples/AddNftAllowance/main.swift
> +            .key(spenderKey.publicKey.single())
Should be `Key.single(spenderKey.publicKey)` since the parameter requires type `Key`

2024-10-30 22:34 UTC, RickyLB commented on Examples/AddNftAllowance/main.swift
> +            .adminKey(env.operatorKey.publicKey)
`.single(<publicKey>)`

2024-10-30 22:34 UTC, RickyLB commented on Examples/AddNftAllowance/main.swift
> +            .supplyKey(env.operatorKey.publicKey)
Same here, needs to be type `Key`

2024-11-07 19:53 UTC, RickyLB approved these changes
LGTM. Merging!

2024-11-07 19:55 UTC, merged